        CREATE TABLE opensea_top100 (
            id INT NOT NULL AUTO_INCREMENT,
            name VARCHAR(100) DEFAULT NULL,
            slug VARCHAR(100) DEFAULT NULL,
            logo VARCHAR(255) DEFAULT NULL,
            one_day_volume DOUBLE DEFAULT NULL,
            one_day_change DOUBLE DEFAULT NULL,
            one_day_sales FLOAT DEFAULT NULL,
            one_day_average_price DOUBLE DEFAULT NULL,
            seven_day_volume DOUBLE DEFAULT NULL,
            seven_day_change DOUBLE DEFAULT NULL,
            seven_day_sales FLOAT DEFAULT NULL,
            seven_day_average_price DOUBLE DEFAULT NULL,
            thirty_day_volume DOUBLE DEFAULT NULL,
            thirty_day_change DOUBLE DEFAULT NULL,
            thirty_day_sales FLOAT DEFAULT NULL,
            thirty_day_average_price DOUBLE DEFAULT NULL,
            total_volume DOUBLE DEFAULT NULL,
            total_sales FLOAT DEFAULT NULL,
            total_supply FLOAT DEFAULT NULL,
            count FLOAT DEFAULT NULL,
            num_owners INT DEFAULT NULL,
            average_price DOUBLE DEFAULT NULL,
            num_reports INT DEFAULT NULL,
            market_cap DOUBLE DEFAULT NULL,
            floor_price DOUBLE DEFAULT NULL,
            created DATETIME DEFAULT NULL,
            PRIMARY KEY (id),
            KEY slug (slug)            
        );


        ALTER TABLE opensea_top100
            ADD banner_image_url VARCHAR(255) DEFAULT NULL,
            ADD created_date VARCHAR(30) DEFAULT NULL,
            ADD description TEXT(5000) DEFAULT NULL,
            ADD discord_url VARCHAR(255) DEFAULT NULL,
            ADD external_url VARCHAR(255) DEFAULT NULL,
            ADD image_url VARCHAR(255) DEFAULT NULL,
            ADD large_image_url VARCHAR(255) DEFAULT NULL,
            ADD medium_username VARCHAR(30) DEFAULT NULL,
            ADD short_description VARCHAR(255) DEFAULT NULL,
            ADD telegram_url VARCHAR(255) DEFAULT NULL,
            ADD twitter_username VARCHAR(30) DEFAULT NULL,
            ADD instagram_username VARCHAR(30) DEFAULT NULL,
            ADD wiki_url VARCHAR(255) DEFAULT NULL
        ;

        CREATE TABLE opensea_top100_new (
            id INT NOT NULL AUTO_INCREMENT,
            name VARCHAR(100) DEFAULT NULL,
            slug VARCHAR(100) DEFAULT NULL,
            logo VARCHAR(255) DEFAULT NULL,
            one_day_volume DOUBLE DEFAULT NULL,
            one_day_change DOUBLE DEFAULT NULL,
            one_day_sales FLOAT DEFAULT NULL,
            one_day_average_price DOUBLE DEFAULT NULL,
            seven_day_volume DOUBLE DEFAULT NULL,
            seven_day_change DOUBLE DEFAULT NULL,
            seven_day_sales FLOAT DEFAULT NULL,
            seven_day_average_price DOUBLE DEFAULT NULL,
            thirty_day_volume DOUBLE DEFAULT NULL,
            thirty_day_change DOUBLE DEFAULT NULL,
            thirty_day_sales FLOAT DEFAULT NULL,
            thirty_day_average_price DOUBLE DEFAULT NULL,
            total_volume DOUBLE DEFAULT NULL,
            total_sales FLOAT DEFAULT NULL,
            total_supply FLOAT DEFAULT NULL,
            count FLOAT DEFAULT NULL,
            num_owners INT DEFAULT NULL,
            average_price DOUBLE DEFAULT NULL,
            num_reports INT DEFAULT NULL,
            market_cap DOUBLE DEFAULT NULL,
            floor_price DOUBLE DEFAULT NULL,
            banner_image_url VARCHAR(255) DEFAULT NULL,
            created_date VARCHAR(30) DEFAULT NULL,
            description TEXT(5000) DEFAULT NULL,
            discord_url VARCHAR(255) DEFAULT NULL,
            external_url VARCHAR(255) DEFAULT NULL,
            image_url VARCHAR(255) DEFAULT NULL,
            large_image_url VARCHAR(255) DEFAULT NULL,
            medium_username VARCHAR(30) DEFAULT NULL,
            short_description VARCHAR(255) DEFAULT NULL,
            telegram_url VARCHAR(255) DEFAULT NULL,
            twitter_username VARCHAR(30) DEFAULT NULL,
            instagram_username VARCHAR(30) DEFAULT NULL,
            wiki_url VARCHAR(255) DEFAULT NULL,
            created DATETIME DEFAULT NULL,
            PRIMARY KEY (id),
            KEY slug (slug)            
        );
